"""
Braintree Gateway Module
Generates working code for Braintree payment gateway
"""

from .base import BaseGateway

class BraintreeGateway(BaseGateway):
    """Braintree payment gateway handler"""
    
    def generate_code(self):
        """
        Generate Python code for Braintree integration
        
        Returns:
            str: Complete Python code snippet
        """
        primary_key = self.get_primary_key()
        
        if not primary_key:
            return "# Error: No Braintree authorization token found"
        
        code = f'''"""
Braintree Payment Gateway Integration
Auto-generated by Gateway-Ripper
"""

import requests
import json
import base64

class BraintreePaymentProcessor:
    """Process payments using Braintree API"""
    
    def __init__(self):
        self.authorization_token = "{primary_key}"
        self.api_base = "https://payments.braintree-api.com"
        self.client_api_base = "https://api.braintreegateway.com"
        
    def get_client_token(self):
        """
        Get client token from Braintree
        
        Returns:
            dict: Response with client token
        """
        # Note: This typically requires server-side implementation
        # This is a placeholder for the client-side flow
        return {{
            "status": "info",
            "message": "Client token generation requires server-side implementation"
        }}
    
    def tokenize_card(self, card_number, exp_month, exp_year, cvv):
        """
        Tokenize card details using Braintree
        
        Args:
            card_number (str): Card number
            exp_month (str): Expiration month (MM)
            exp_year (str): Expiration year (YY or YYYY)
            cvv (str): Card verification value
            
        Returns:
            dict: Response from Braintree API
        """
        url = f"{{self.api_base}}/graphql"
        
        # Format expiration date
        exp_date = f"{{exp_month}}/{{exp_year}}"
        
        # GraphQL mutation for tokenization
        query = """
        mutation TokenizeCreditCard($input: TokenizeCreditCardInput!) {{
            tokenizeCreditCard(input: $input) {{
                token
                creditCard {{
                    brand
                    last4
                    expirationMonth
                    expirationYear
                    binData {{
                        prepaid
                        healthcare
                        debit
                        durbinRegulated
                        commercial
                        payroll
                        issuingBank
                        countryOfIssuance
                        productId
                    }}
                }}
            }}
        }}
        """
        
        variables = {{
            "input": {{
                "creditCard": {{
                    "number": card_number,
                    "expirationDate": exp_date,
                    "cvv": cvv
                }}
            }}
        }}
        
        headers = {{
            "Authorization": f"Bearer {{self.authorization_token}}",
            "Content-Type": "application/json",
            "Braintree-Version": "2019-01-01"
        }}
        
        payload = {{
            "query": query,
            "variables": variables
        }}
        
        try:
            response = requests.post(url, json=payload, headers=headers)
            return response.json()
        except Exception as e:
            return {{"error": {{"message": str(e)}}}}
    
    def check_card(self, card_number, exp_month, exp_year, cvv):
        """
        Check card validity by tokenizing
        
        Args:
            card_number (str): Card number
            exp_month (str): Expiration month
            exp_year (str): Expiration year
            cvv (str): Card verification value
            
        Returns:
            dict: Result with status and message
        """
        result = self.tokenize_card(card_number, exp_month, exp_year, cvv)
        
        if "errors" in result or "error" in result:
            error_msg = "Card validation failed"
            if "errors" in result:
                error_msg = result["errors"][0].get("message", error_msg)
            elif "error" in result:
                error_msg = result["error"].get("message", error_msg)
            
            return {{
                "status": "declined",
                "message": error_msg,
                "card_last4": card_number[-4:] if len(card_number) >= 4 else "****"
            }}
        
        if "data" in result and "tokenizeCreditCard" in result["data"]:
            card_data = result["data"]["tokenizeCreditCard"]["creditCard"]
            return {{
                "status": "valid",
                "message": "Card details are valid",
                "token": result["data"]["tokenizeCreditCard"]["token"],
                "card_brand": card_data.get("brand", "unknown"),
                "card_last4": card_data.get("last4", "****")
            }}
        
        return {{
            "status": "unknown",
            "message": "Unable to determine card status",
            "card_last4": card_number[-4:] if len(card_number) >= 4 else "****"
        }}
    
    def get_test_cards(self):
        """
        Get Braintree test card numbers
        
        Returns:
            dict: Test card information
        """
        return {{
            "visa": "4111111111111111",
            "mastercard": "5555555555554444",
            "amex": "378282246310005",
            "discover": "6011111111111117",
            "processor_declined": "4000111111111115"
        }}


# Example usage
if __name__ == "__main__":
    processor = BraintreePaymentProcessor()
    
    # Test with Braintree test card
    result = processor.check_card(
        card_number="4111111111111111",
        exp_month="12",
        exp_year="2025",
        cvv="123"
    )
    
    print(json.dumps(result, indent=2))
'''
        
        return self.format_code(code)
    
    def get_test_cards(self):
        """
        Get Braintree test card numbers
        
        Returns:
            dict: Test card information
        """
        return {
            "visa": "4111111111111111",
            "mastercard": "5555555555554444",
            "amex": "378282246310005",
            "discover": "6011111111111117",
            "processor_declined": "4000111111111115"
        }
