"""
Stripe Gateway Module
Generates working code for Stripe payment gateway
"""

from .base import BaseGateway

class StripeGateway(BaseGateway):
    """Stripe payment gateway handler"""
    
    def generate_code(self):
        """
        Generate Python code for Stripe integration
        
        Returns:
            str: Complete Python code snippet
        """
        primary_key = self.get_primary_key()
        
        if not primary_key:
            return "# Error: No Stripe API key found"
        
        # Determine if it's a test or live key
        key_type = "TEST" if "test" in primary_key else "LIVE"
        
        code = f'''"""
Stripe Payment Gateway Integration
Auto-generated by Gateway-Ripper
Key Type: {key_type}
"""

import requests
import json

class StripePaymentProcessor:
    """Process payments using Stripe API"""
    
    def __init__(self):
        self.publishable_key = "{primary_key}"
        self.api_base = "https://api.stripe.com/v1"
        
    def create_token(self, card_number, exp_month, exp_year, cvc):
        """
        Create a payment token from card details
        
        Args:
            card_number (str): Card number (16 digits)
            exp_month (str): Expiration month (MM)
            exp_year (str): Expiration year (YY or YYYY)
            cvc (str): Card security code (3-4 digits)
            
        Returns:
            dict: Response from Stripe API
        """
        url = f"{{self.api_base}}/tokens"
        
        data = {{
            "card[number]": card_number,
            "card[exp_month]": exp_month,
            "card[exp_year]": exp_year,
            "card[cvc]": cvc
        }}
        
        headers = {{
            "Authorization": f"Bearer {{self.publishable_key}}",
            "Content-Type": "application/x-www-form-urlencoded"
        }}
        
        try:
            response = requests.post(url, data=data, headers=headers)
            return response.json()
        except Exception as e:
            return {{"error": {{"message": str(e)}}}}
    
    def create_payment_method(self, card_number, exp_month, exp_year, cvc):
        """
        Create a PaymentMethod (newer Stripe API)
        
        Args:
            card_number (str): Card number
            exp_month (str): Expiration month
            exp_year (str): Expiration year
            cvc (str): Card security code
            
        Returns:
            dict: Response from Stripe API
        """
        url = f"{{self.api_base}}/payment_methods"
        
        data = {{
            "type": "card",
            "card[number]": card_number,
            "card[exp_month]": exp_month,
            "card[exp_year]": exp_year,
            "card[cvc]": cvc
        }}
        
        headers = {{
            "Authorization": f"Bearer {{self.publishable_key}}",
            "Content-Type": "application/x-www-form-urlencoded"
        }}
        
        try:
            response = requests.post(url, data=data, headers=headers)
            return response.json()
        except Exception as e:
            return {{"error": {{"message": str(e)}}}}
    
    def check_card(self, card_number, exp_month, exp_year, cvc):
        """
        Check card validity by creating a token
        
        Args:
            card_number (str): Card number
            exp_month (str): Expiration month
            exp_year (str): Expiration year
            cvc (str): Card security code
            
        Returns:
            dict: Result with status and message
        """
        result = self.create_token(card_number, exp_month, exp_year, cvc)
        
        if "error" in result:
            error_msg = result["error"].get("message", "Unknown error")
            error_code = result["error"].get("code", "unknown")
            
            return {{
                "status": "declined",
                "message": error_msg,
                "code": error_code,
                "card_last4": card_number[-4:] if len(card_number) >= 4 else "****"
            }}
        else:
            return {{
                "status": "valid",
                "message": "Card details are valid",
                "token": result.get("id"),
                "card_brand": result.get("card", {{}}).get("brand", "unknown"),
                "card_last4": result.get("card", {{}}).get("last4", "****")
            }}
    
    def get_test_cards(self):
        """
        Get Stripe test card numbers
        
        Returns:
            dict: Test card information
        """
        return {{
            "success": "4242424242424242",
            "declined": "4000000000000002",
            "insufficient_funds": "4000000000009995",
            "expired": "4000000000000069",
            "incorrect_cvc": "4000000000000127",
            "processing_error": "4000000000000119"
        }}


# Example usage
if __name__ == "__main__":
    processor = StripePaymentProcessor()
    
    # Test with Stripe test card
    result = processor.check_card(
        card_number="4242424242424242",
        exp_month="12",
        exp_year="2025",
        cvc="123"
    )
    
    print(json.dumps(result, indent=2))
'''
        
        return self.format_code(code)
    
    def get_test_cards(self):
        """
        Get Stripe test card numbers
        
        Returns:
            dict: Test card information
        """
        return {
            "success": "4242424242424242",
            "declined": "4000000000000002",
            "insufficient_funds": "4000000000009995",
            "expired": "4000000000000069",
            "incorrect_cvc": "4000000000000127",
            "processing_error": "4000000000000119"
        }
